project:
  type: website
  output-dir: _site
  resources:
    - static/
    - assets/

website:
  site-url: https://bizzup745.github.io/bizzupdepot-website/
  title: "Bizz Trading Inc. (Bizzup Depot)"
  favicon: /bizzupdepot-website/assets/img/logo.png

  navbar:
    logo: /bizzupdepot-website/assets/img/logo.png
    left:
      - text: "About"
        href: /bizzupdepot-website/en/about.html
      - text: "Services"
        href: /bizzupdepot-website/#services
      - text: "Product Catalog"
        href: /bizzupdepot-website/en/catalog.html
      - text: "Contact"
        href: /bizzupdepot-website/en/contact.html
    right:
      - text: "ENGLISH"
        href: /bizzupdepot-website/en/index.html
      - text: "한국어"
        href: /bizzupdepot-website/ko/index.html

  page-footer:
    left: "© 2025 Bizz Trading Inc."
    right: "745 85th Ave STE E, Oakland, CA · info@bizzupdepot.com · (510) 542-1324"

format:
  html:
    theme: cosmo
    css:
      - /bizzupdepot-website/assets/agency.css
      - /bizzupdepot-website/assets/styles.scss
    toc: false
    smooth-scroll: true
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
