# _quarto.yml (루트)
project:
  type: website
  render: [en, ko]   # ← 루트에서 render 하면 en/ ko/ 둘 다 같이 빌드

website:
  site-url: https://bizzup745.github.io/bizzupdepot-website/
  title: "Bizz Trading Inc. (Bizzup Depot)"
  favicon: assets/img/logo.png        # ← 상대 경로
  navbar:
    logo: assets/img/logo.png         # ← 상대 경로
    left:
      - text: "About"
        href: en/about.qmd            # ← QMD 상대경로 (Quarto가 .html로 변환)
      - text: "Services"
        href: en/index.qmd#services
      - text: "Product Catalog"
        href: en/catalog.qmd
      - text: "Contact"
        href: en/contact.qmd
    right:
      - text: "ENGLISH"
        href: en/index.qmd
      - text: "한국어"
        href: ko/index.qmd

format:
  html:
    theme: cosmo
    css:
      - assets/agency.css             # ← 상대 경로
      - styles.scss                   # ← 상대 경로
    toc: false
    smooth-scroll: true
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />
